# Generated by Django 4.2.2 on 2023-07-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('propic', models.FileField(default='anonymous.jpg', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_price', models.IntegerField()),
                ('pro_qty', models.IntegerField()),
                ('pro_image', models.FileField(default='pro.jpg', upload_to='Product/')),
                ('pro_desc', models.TextField(max_length=500)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.seller_user')),
            ],
        ),
    ]
