# Generated by Django 4.2.1 on 2023-06-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='unknown.jpg', null=True, upload_to='media/'),
        ),
    ]
