# Generated by Django 4.1.7 on 2023-04-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=200)),
                ('pimage', models.FileField(default='apro.jpg', upload_to='pimage')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.seller_user')),
            ],
        ),
    ]
