# Generated by Django 4.1.1 on 2022-11-14 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('tosee', models.CharField(max_length=100)),
                ('todepartment', models.CharField(max_length=100)),
                ('take_photo', models.ImageField(default='', upload_to='visitor')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('made_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_status', models.CharField(default='Entry', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.PositiveIntegerField()),
                ('mobile', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('usertype', models.CharField(choices=[('Vistor', 'Visitor'), ('user', 'user')], max_length=100)),
            ],
        ),
    ]
