# Generated by Django 4.1.1 on 2022-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='current_status',
            field=models.CharField(default='Entry', max_length=10),
        ),
    ]
