# Generated by Django 4.1.1 on 2023-01-26 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_address_signup_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='mobile',
            new_name='emp_code',
        ),
        migrations.RemoveField(
            model_name='log',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='log',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='log',
            name='todepartment',
        ),
        migrations.RemoveField(
            model_name='log',
            name='tosee',
        ),
        migrations.AddField(
            model_name='log',
            name='amount',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='log',
            name='reason',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
