# Generated by Django 4.1.6 on 2023-02-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_petty_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petty_amount',
            name='amount_present',
            field=models.IntegerField(default=0),
        ),
    ]
