# Generated by Django 4.1.7 on 2023-03-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.FileField(default='anonymous.png', upload_to='product_image/'),
        ),
    ]
