# Generated by Django 4.1.7 on 2023-03-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0003_user_profilepic_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.FileField(default='anonymous.png', upload_to='profile_pic/'),
        ),
    ]
