# Generated by Django 4.1.7 on 2023-03-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0002_products_product_image'),
        ('app_buyer', '0004_alter_user_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_time', models.DateTimeField(auto_now_add=True)),
                ('buyer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buyer.user')),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.products')),
            ],
        ),
    ]
