# Generated by Django 4.0.6 on 2022-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chk',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
