# Generated by Django 4.1 on 2022-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='anonymous.png', upload_to='buyer_images'),
        ),
    ]
