# Generated by Django 4.1 on 2022-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.CharField(max_length=10)),
                ('productdesc', models.CharField(max_length=500)),
                ('productpic', models.FileField(default='anonymous.png', upload_to='product_images')),
            ],
        ),
    ]
