# Generated by Django 4.1 on 2022-09-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0003_product_seller_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Userseller',
        ),
    ]
