# Generated by Django 4.1 on 2022-09-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_seller', '0004_delete_product_delete_userseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('pic', models.FileField(default='anonymous.png', upload_to='buyer_images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.CharField(max_length=10)),
                ('productdesc', models.CharField(max_length=500)),
                ('productpic', models.FileField(default='anonymous.png', upload_to='product_images')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.userseller')),
            ],
        ),
    ]
